Lab2 – Python Data Structures, NumPy, and Pandas

Part1: Standard Data Structures
1. Print element 5 from the following nested tuple:
tup = 4, 5, 6
nested_tup = (4, 5, 6), (7, 8)

In [6]:
tup = 4,5,6 
nested_tup = (4,5,6),(7,8)
print(nested_tup[0][1])

5


2. Use the following to build a dictionary d1 = {'a' : 'some value', 'b' : [1, 2, 3, 4]},
then get the element with key ‘a’ in the dictionary.

In [9]:
d1 = {'a' : 'some value', 
      'b' : [1, 2, 3, 4]}
print(d1['a'])

some value


3. Add the following element to the dictionary d1[5] = Another value'

In [10]:
d1[5] = 'another value'

4. Print the dictionary then delete the added element in step 3 using del d1[5], then
print the dictionary again.

In [11]:
print(d1)
del d1[5]
print(d1)

{'a': 'some value', 'b': [1, 2, 3, 4], 5: 'another value'}
{'a': 'some value', 'b': [1, 2, 3, 4]}


5. Update the dictionary like this d1.update({'b' : 'foo', 'c' : 12}), then print d1.

In [ ]:
d1.update({'b' : 'foo', 'c' : 12})
print(d1)

6. Type the following code and print the by_letter dictionary. Explain the output.
words = ['apple', 'bat', 'bar', 'atom', 'book']
by_letter = {}
for word in words:
letter = word[0]
if letter not in by_letter:
by_letter[letter] = [word]
else:
by_letter[letter].append(word)

In [12]:
words = ['apple', 'bat', 'bar', 'atom', 'book']
by_letter = {}
for word in words:
    letter = word[0]
    if letter not in by_letter:
        by_letter[letter] = [word]
    else:
        by_letter[letter].append(word)
print(by_letter)

{'a': ['apple', 'atom'], 'b': ['bat', 'bar', 'book']}


We are looping through each word and looking at the first letter of each word, we save the letter to a variable and then if the letter is not already in the dictionary, it is added. Each word is added to the dictionary under the key using the first letter of the word.

Part2: NumPy
1. Type the following code and explain the results.
import numpy as np
np.array([1,1,2,2,3])
print (type(np.array([1,1,2,2,3])))
x = np.array([1,1,2,2,3, 5])
print (x)
print (x.shape)
y = x.reshape((2,3))
print(y)
print (y.shape)

In [13]:
import numpy as np
np.array([1,1,2,2,3])
print (type(np.array([1,1,2,2,3])))
x = np.array([1,1,2,2,3, 5])
print (x)
print (x.shape)
y = x.reshape((2,3))
print(y)
print (y.shape)

<class 'numpy.ndarray'>
[1 1 2 2 3 5]
(6,)
[[1 1 2]
 [2 3 5]]
(2, 3)


np.array([1,1,2,2,3])
print (type(np.array([1,1,2,2,3])))
The first print is displaying the data type of the numpy array

x = np.array([1,1,2,2,3, 5])
print (x)
The second print is showing how numpy converts the array into a single-dimensional array

print (x.shape)
The third print shows a dataset with 1 colum and 6 rows

y = x.reshape((2,3))
print(y)
The 4th print shows a reformated state of the data where it has been changed to be 2 rows and 3 columns

print (y.shape)
The 5th print confirms the 2 rows by 3 columns

2. Type the following code, and explain the results:
a = np.arange(1, 20, 2)
print (a)
b = np.array([])
print (b)
c = np.zeros(6)
print (c)
d = np.ones(6)
print (d)
e = np.array(range(1,6))
print (e)
np.linspace(0, 5, 50)

In [19]:
a = np.arange(1, 20, 2)
print (a)
b = np.array([])
print (b)
c = np.zeros(6)
print (c)
d = np.ones(6)
print (d)
e = np.array(range(1,6))
print (e)
np.linspace(0, 5, 50)

[ 1  3  5  7  9 11 13 15 17 19]
[]
[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[1 2 3 4 5]


array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])


a = np.arange(1, 20, 2)
print (a)
First we are going to create a single-dimension array starting at 1 going until 20 but only adding every 2nd number. (Start stop step)

b = np.array([])
print (b)
Second is an empty array, showing that it still exists

c = np.zeros(6)
print (c)
Third shows an array that fills with the integers quantity of zeroes

d = np.ones(6)
print (d)
Fourth shows an array that fills with the integers quantity of 1s

e = np.array(range(1,6))
print (e)
Fifth shows a single-dimension array fills with the numbers 1-5 due to the range being 1,6 (starts at 1 ends at 5)

np.linspace(0, 5, 50)
Sixth shows the creation of array between 0 and 5 but dividing the quantity of steps by 50 and then placing each step in the array

3. Type the following code, and explain the results:
import numpy as np
y = np.array([6, 10, 3, 4, 5, 6, 7])
print (y.argmin())
i = np.where(y>4)
print (i)
y.sort()
x = y.copy()
print (x)

In [20]:
import numpy as np
y = np.array([6, 10, 3, 4, 5, 6, 7])
print (y.argmin())
i = np.where(y>4)
print (i)
y.sort()
x = y.copy()
print (x)

2
(array([0, 1, 4, 5, 6], dtype=int64),)
[ 3  4  5  6  6  7 10]


y = np.array([6, 10, 3, 4, 5, 6, 7])
The first line initializes a numpy array y with the given values.

print (y.argmin())
the second line argmin() returns the index of the minimum element in the array y. The index 2 will be printed for the value 3

i = np.where(y>4)
print (i)
the third line np.where() returns the index of each element that satisfies the equation in this case where y is greater than 4

y.sort()
the fourth line sort() function will sort the array y in ascending order

x = y.copy()
print (x)
The fifth line stores a copy of the array but in a different place in memory
The last line will print the copy of the array showing the copy exists


4. Type the following code and explain the results :
x = np.random.random_sample((3,3))
y = np.random.random_sample((3,3))
print (np.dot(x, y))
print (np.cross(x, y))
print (np.linalg.det(x))
print (np.linalg.inv(x))

In [25]:
x = np.random.random_sample((3,3))
y = np.random.random_sample((3,3))
print (np.dot(x, y))
print (np.cross(x, y))
print (np.linalg.det(x))
print (np.linalg.inv(x))

[[0.90599078 0.73716421 0.77716878]
 [0.69367423 0.62461997 0.52559693]
 [0.21924161 0.22965419 0.1313074 ]]
[[ 0.2774143  -0.39922478 -0.03039608]
 [-0.25724972  0.30209385 -0.06447518]
 [-0.04875136  0.02549865 -0.00568403]]
0.017399881621827033
[[  9.40211387 -17.67664939  19.01343807]
 [-14.42356448  30.48325875 -33.62321787]
 [  5.19300296 -11.21383574  14.23763396]]


y = np.random.random_sample((3,3)):
The first line creates a 3x3 matrix x with random values between 0 and 1.
y = np.random.random_sample((3,3))
this second line creates a 3x3 matrix y with random values between 0 and 1.

print(np.dot(x, y)):
The np.dot function calculates the dot product of two matrices. It produces the outcome of matrice multiplcation and stores the values
|A B| . |E F| = |A*E+B*G A*F+B*H|
|C D|   |G H|   |C*E+D*G C*F+D*H|

print(np.cross(x, y)):
The np.cross function calculates the cross multiplcation of rows and columns from each matrix and then stores it in a new matrix
|A B|   |E F| = |A*E B*F|
|C D|   |G H|   |C*G D*H|

print(np.linalg.det(x)):
The np.linalg.det function calculates the determinant of a matrix. The determinant can be used to solve other mathematical problems

print(np.linalg.inv(x)):
This will display the inverse of the matrix given

5. Type the following code and explain the results:
arr = np.arange(10)
print (arr)
print (arr[5])
print (arr[5:8])

In [26]:
arr = np.arange(10)
print (arr)
print (arr[5])
print (arr[5:8])

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]


arr = np.arange(10):
This line initializes an array with values ranging from 0 to 9.

print(arr):
This line prints the entire array arr, so you will see: [0 1 2 3 4 5 6 7 8 9].

print(arr[5]):
This line prints the element at index 5 of the array which is 5.


print(arr[5:8]):
This line prints a splice of the array which will be 5,6,7


6. Type the following code, and explain the results:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print (names)
print ('*******************')
print (data)
print ('*******************')
print (names == 'Bob')
print ('*******************')
print (data[names == 'Bob'])
print ('*******************')
print (data[names == 'Bob', 2:])
print ('*******************')
print (data[names == 'Bob', 3])
print ('*******************')
mask = (names == 'Bob') | (names == 'Will')
print ('*******************')
print (mask)
print ('*******************')
print (data[mask])

In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print (names)
print ('*******************')
print (data)
print ('*******************')
print (names == 'Bob')
print ('*******************')
print (data[names == 'Bob'])
print ('*******************')
print (data[names == 'Bob', 2:])
print ('*******************')
print (data[names == 'Bob', 3])
print ('*******************')
mask = (names == 'Bob') | (names == 'Will')
print ('*******************')
print (mask)
print ('*******************')
print (data[mask])

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
*******************
[[-0.17793108 -1.17535484  0.22395287 -0.83612657]
 [-0.6436291  -0.93540864  1.04532562 -0.3049099 ]
 [ 1.23968175  1.19493869  1.1058872   0.52002939]
 [ 1.48123082  1.18671567  0.6963318   2.28025648]
 [ 1.83555869  0.03440481 -0.31289654  1.57093094]
 [ 0.72965847 -2.32555888  0.28642496 -0.78365366]
 [-1.27099383  1.33424583  1.30367296 -0.63633232]]
*******************
[ True False False  True False False False]
*******************
[[-0.17793108 -1.17535484  0.22395287 -0.83612657]
 [ 1.48123082  1.18671567  0.6963318   2.28025648]]
*******************
[[ 0.22395287 -0.83612657]
 [ 0.6963318   2.28025648]]
*******************
[-0.83612657  2.28025648]
*******************
*******************
[ True False  True  True  True False False]
*******************
[[-0.17793108 -1.17535484  0.22395287 -0.83612657]
 [ 1.23968175  1.19493869  1.1058872   0.52002939]
 [ 1.48123082  1.18671567  0.6963318   2.28025648]
 [ 1.835558

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']):
Creates a numpy array names with specified string values.

data = np.random.randn(7, 4):
Creates a 7x4 matrix data with random values sampled from the standard normal distribution.

print(names):
Prints the names array.

print('*******************') and print(data):
Prints a separator line and then the data array.

print(names == 'Bob'):
Performs a comparison of the names array to the string 'Bob', producing a boolean array indicating where the string 'Bob' appears in the names array.

print(data[names == 'Bob']):
Uses boolean indexing to select the rows of data corresponding to the positions where 'Bob' appears in the names array.

print(data[names == 'Bob', 2:]):
Similar to the previous line, but additionally uses slicing to select only columns 2 and onwards of the rows corresponding to 'Bob'.

print(data[names == 'Bob', 3]):
Selects only column 3 of the rows corresponding to 'Bob'.

mask = (names == 'Bob') | (names == 'Will'):
The line mask = (names == 'Bob') | (names == 'Will') is checking each name in the names array to see if it's either 'Bob' or 'Will'. If it is, it records a True for that name; if not, it records a False.

print(mask):
Prints the mask array.

print(data[mask]):
Uses the mask array for boolean indexing to select the rows of data corresponding to the positions where names is either 'Bob' or 'Will'.


7. Given the following matrix:
import numpy as np
M1 = np.array([[2, 4, 6, 8, 10],
[3, 6, 9, -12, -15],
[4, 8, 12, 16, -20],
[5, -10, 15, -20, 25]])
- Print the 1st and 2nd row, and for columns, we want the first, second, and third
column.
- Print all rows and third columns.
- Print the first row and all columns.
- Print the first three rows and first 2 columns.

In [31]:
import numpy as np
M1 = np.array([[2, 4, 6, 8, 10],
[3, 6, 9, -12, -15],
[4, 8, 12, 16, -20],
[5, -10, 15, -20, 25]])

print(M1[0:2, 0:3])
print(M1[:, 2])
print(M1[0, :])
print(M1[0:3, 0:2])


[[2 4 6]
 [3 6 9]]
[ 6  9 12 15]
[ 2  4  6  8 10]
[[2 4]
 [3 6]
 [4 8]]



8. Create a numpy array and name it weight_lb (give acceptable weight values for 10
humans).
- Multiply by 0.453592 to go from pounds to kilograms and store the resulting numpy
array as np_weight_kg
- Create np_hight_m numpy array and store acceptable height values for 10 humans.
- Calculate the BMI of each player using the following equation:
- BMI = weight(kg)/ height(m) ** 2
- Save the resulting numpy array as bmi
- Print out bmi
- Create a boolean numpy array: the element of the array should be True if the
corresponding baseball player’s BMI is below 21. You can use the < operator for this.
Name the array light and print it.


In [36]:
import numpy as np
weight_lb = np.array([150, 160, 170, 180, 190, 200, 210, 220, 230, 240])
np_weight_kg = weight_lb * 0.453592
np_height_m = np.array([1.70, 1.75, 1.80, 1.85, 1.90, 1.95, 2.00, 2.05, 2.10, 2.15])
bmi = np_weight_kg / np_height_m ** 2
print(bmi)
light = bmi < 21
print(light)

[23.54283737 23.69786776 23.79958025 23.85582469 23.87326316 23.85756739
 23.81358    23.74544676 23.65672562 23.55047701]
[False False False False False False False False False False]
